name: Test allure report

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project which set in playwright.config.ts'
        required: true
        default: 'PoC with Playwright'
        type: choice
        options:
          - 'PoC with Playwright'
      environment:
        description: 'Environment to run (RC or QC)'
        required: true
        default: 'RC'
        type: choice
        options:
          - 'RC'
          - 'QC'
      suite:
        description: 'Suite to Run (all or specific suite)'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'example'
      tagorname:
        description: 'Tag or Test Name to run (leave empty or specify a @tag and test name)'
        required: false
        default: ''
        type: string

jobs:
  test:
    runs-on: ubuntu-22.04 # Set the operating system for the job
    permissions: write-all
    

    steps:
      - name: Get Allure history # Step to retrieve Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: report/${{ github.event.inputs.environment }} # Specify the branch to retrieve Allure history from
          path: allure-history # Set the destination path for Allure history

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      
      - name: Install dependencies
        run:
          npm ci

      - name: Run Playwright tests
        env:
          ALLURE_RESULTS_DIR: test-results/${{ github.event.inputs.environment }}/jsons
          ENV: ${{ github.event.inputs.environment }}
          headless: true
        run: |
          pwd
          ll
          xvfb-run playwright test --project='PoC with Playwright' --debug
        # run: |
        #   if [ "${{ github.event.inputs.suite }}" = "all" ] && [ -z "${{ github.event.inputs.tagorname }}" ]; then
        #     npx playwright test --project='${{ github.event.inputs.project }}' --debug
        #   elif [ "${{ github.event.inputs.suite }}" != "all" ] && [ -z "${{ github.event.inputs.tagorname }}" ]; then
        #     npx playwright test --project='${{ github.event.inputs.project }}' -g '${{ github.event.inputs.suite }}' --debug
        #   else
        #     npx playwright test --project='${{ github.event.inputs.project }}' -g '${{ github.event.inputs.tagorname }}' --debug
        #   fi

      - name: Allure report action # Step to generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always() # Execute even if previous steps fail
        with:
          allure_results: test-results/${{ github.event.inputs.environment }}/jsons # Specify the directory containing Allure results
          allure_history: allure-history # Specify the directory to store Allure history
          keep_reports: 5 # Specify the number of previous reports to keep

      - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
        if: always() # Execute even if previous steps fail
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Provide the GitHub token for authentication
          publish_branch: report/${{ github.event.inputs.environment }} # Specify the branch to publish the report to
          publish_dir: ${{ github.run_number }} # Specify the directory containing the report
